name: build library

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  PROJECT_PATH: './BimGisCad/BimGisCad.csproj'
  OUTPUT_DIRECTORY: ${{github.workspace}}\output

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
    #- name: Restore dependencies
    #  run: dotnet restore
    - name: Build
      run: dotnet build ${{ env.PROJECT_PATH}}
    - name: Pack
      run: dotnet pack ${{ env.PROJECT_PATH}} --output ${{ env.OUTPUT_DIRECTORY }}
    - uses: actions/upload-artifact@v2
      with:
        name: BimGisCad
        path: ${{ env.OUTPUT_DIRECTORY }}
    #- name: Add source to nuget
    #  run: dotnet nuget add source --username Hutsimbl --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Hutsimbl/index.json"
    - name: Publish the package to the repository
      run: dotnet nuget push ${{env.OUTPUT_DIRECTORY}}\*.nupkg --api-key ${{ secrets.PACKAGE_TOKEN}} --source https://github.com/Hutsimbl/bimgiscadTestCI
      #env:
      #  NUGET_AUTH_TOKEN: ${{ github.token }}
